# Generated by Django 4.0.4 on 2022-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
