# Generated by Django 4.0.6 on 2022-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('aboute', models.TextField(max_length=700)),
                ('price', models.IntegerField(default=1)),
                ('old_price', models.IntegerField(default=2)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
