# Generated by Django 4.0.6 on 2022-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivals_img', models.ImageField(upload_to='')),
                ('arrivals_title', models.CharField(max_length=200)),
                ('arrivals_price', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
