# Generated by Django 4.0.4 on 2022-08-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0002_myuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_url',
        ),
    ]
