# Generated by Django 4.0.4 on 2022-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_remove_product_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(auto_created=True, max_length=50),
        ),
    ]
