# Generated by Django 4.0.6 on 2022-07-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_arrivals_alter_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivals',
            name='arrivals_url',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
