# Generated by Django 4.0.6 on 2022-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0004_arrivals_arrivals_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivals',
            name='arrivals_url',
            field=models.CharField(max_length=200),
        ),
    ]
