# Generated by Django 4.0.6 on 2022-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0005_alter_arrivals_arrivals_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('aboute', models.TextField(max_length=700)),
            ],
        ),
    ]
