# Generated by Django 4.0.4 on 2022-08-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='custome_user',
        ),
    ]
