# Generated by Django 4.0.4 on 2022-08-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0007_rename_user_profile_custome_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user_image',
        ),
    ]
