# Generated by Django 4.0.6 on 2022-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0007_blog_title_url_alter_arrivals_arrivals_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
    ]
