# Generated by Django 4.0.6 on 2022-07-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0009_products_products_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arrivals',
            new_name='Arrival',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
