# Generated by Django 4.0.6 on 2022-07-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0011_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_orgabiser',
            field=models.BooleanField(default=False),
        ),
    ]
