# Generated by Django 4.0.6 on 2022-07-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0012_myuser_is_agent_myuser_is_orgabiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_orgabiser',
            new_name='is_organiser',
        ),
    ]
