# Generated by Django 4.0.4 on 2022-08-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='biooo', max_length=100),
        ),
    ]
