# Generated by Django 4.1 on 2022-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0015_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=998949949494),
        ),
    ]
