# Generated by Django 4.1 on 2022-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='text',
            field=models.TextField(default=1, max_length=700),
            preserve_default=False,
        ),
    ]
