# Generated by Django 4.1 on 2022-09-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0021_product_fake_rate_1_product_fake_rate_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fake_rate_1',
            new_name='rate_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fake_rate_2',
            new_name='rate_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fake_rate_3',
            new_name='rate_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fake_rate_4',
            new_name='rate_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fake_rate_5',
            new_name='rate_5',
        ),
    ]
