# Generated by Django 4.1 on 2022-09-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0024_remove_product_rate_1_choices_product_rate_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate_choices',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=8),
        ),
    ]
