# Generated by Django 4.1 on 2022-09-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0026_product_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sender',
        ),
    ]
