# Generated by Django 4.1 on 2022-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0029_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
