# Generated by Django 4.1 on 2022-09-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0030_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate_choices',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_choices', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=8)),
                ('qaysi_mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furn.product')),
            ],
        ),
    ]
