# Generated by Django 4.1 on 2022-09-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0031_remove_product_rate_choices_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
