# Generated by Django 4.1 on 2022-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0032_rate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_choices',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=8),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
