# Generated by Django 4.1 on 2022-09-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0033_product_rate_choices_delete_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate_choices',
        ),
        migrations.AddField(
            model_name='product',
            name='rate_1',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_2',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_3',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_4',
            field=models.CharField(default='4', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_5',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
