# Generated by Django 4.1 on 2022-09-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0034_remove_product_rate_choices_product_rate_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate_1',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_5',
        ),
    ]
