# Generated by Django 4.1 on 2022-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0036_product_secret_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secret',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
