# Generated by Django 4.1 on 2022-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0038_product_title_en_product_title_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='blog',
            name='aboute_en',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='aboute_uz',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
