# Generated by Django 4.1 on 2022-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0039_remove_product_title_en_remove_product_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
