# Generated by Django 4.1 on 2022-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0040_product_title_en_product_title_uz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
