# Generated by Django 4.1 on 2022-10-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0042_carousel_title_en_carousel_title_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='aboute_en',
            field=models.TextField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='aboute_uz',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
